baseURL = 'https://lucasalavapena.github.io/'
title = 'Lucas Alava Peña'
theme = 'archie_fork'
languageCode = 'en-us'
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableGitInfo = true
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
sectionPagesMenu = 'main'


[params]
	mode="dark"
	useCDN=false
	katex = true # enable KaTeX support
	onion="d7uiikaacted6bvtglizgrit5ve3sqmk2v7eo5oqofzms7nuaonwmhad"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lucasalavapena"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/lucasalavapena/"

[[params.social]]
name = "Leetcode"
icon = "leetcode"
url = "https://leetcode.com/lucasalavapena/"


